SECRET_KEY = 'this_is_secret_123'
EVENT_MESSAGE = 'new_msg'

SESSION_DETECTION_THRESHOLD = 'detection_threshold'
SESSION_CLASSIFICATION_THRESHOLD = 'classification_threshold'
SESSION_MAX_DETECTIONS = 'max_detections'

DEFAULT_CONFIDENCE_THRESHOLD = 0.01
DEFAULT_MAX_DETECTIONS = 10
